### ISSUE TITLE
Fix string escaping/unescaping in Erlang implementation

### ISSUE THREAD

**Issue by kanaka** [kanaka/mal#100]
@nlfiedler I recently added some tests that do better coverage of string escaping and unescaping. In particular, this allows ANSI escape codes to be used in output to support. For example, being able to run the mal/clojurewest2014.mal presentation correctly.

I was able to fix the escaping/unescaping for all the other languages, but I'm not familiar enough with Erlang to be able to fix it easily. I think the escaping in printer.erl is okay, but the unescaping in reader.erl is missing the "\n" case. At least, that appears to be the issue. Do you think you could take a look at it?

You can reproduce the failures with:

```
make test^erlang^step4
```

**Comment by kanaka** [comment]
BTW, here is the line in the travis test output where the failures start: https://travis-ci.org/kanaka/mal/jobs/88477516#L440

**Comment by nlfiedler** [comment]
Certainly, I'll take a look this week.
