### ISSUE TITLE
Missing regression testing

### ISSUE THREAD

**Issue by dubek** [kanaka/mal#107]
During the development of the Tcl implementation I found it important in some steps to verify that I haven't broken something that was working OK earlier. In my case, while implementing TCO in step 5 I broke `let*` by mistake, but no tests covered it. However, running the `tests/step4_if_fn_do.mal` test file against my `step5_tco.tcl` program quickly showed that `let*` is broken.

I wrote a small regression tester bash script (for Tcl - see code below) that runs all the test cases from previous steps (except step0 and step1) against the given step implementation. For example, if you run the script with `step6` it'll concatenate the tests files for step2, step3, step4, step5 and step6 and feed the combined test file into the step6 program. 

A better implementation would be in the Makefile with all the info about RUNSTEP and STEP_TO_PROG available there. We can also improve `runtest.py` to accept *several* test files and execute them one after the other (reporting total scores of success/failed tests at the end).

#### regtest.sh

```bash
#!/bin/bash

step=$1

if [ -z $step ] ; then
  echo "Usage: $0 step"
  echo "Example: $0 step9"
  exit 1
fi

step0_regs="step0"
step1_regs="step1"
step2_regs="step2"
step3_regs="$step2_regs step3"
step4_regs="$step3_regs step4"
step5_regs="$step4_regs step5"
step6_regs="$step5_regs step6"
step7_regs="$step6_regs step7"
step8_regs="$step7_regs step8"
step9_regs="$step8_regs step9"
stepA_regs="$step9_regs stepA"

projectdir=$(dirname $0)
cd $projectdir/tcl

testfiles=""
eval "regsteps=\$${step}_regs"
for s in $regsteps ; do
  testfile=$(echo ../tests/$s*.mal)
  testfiles="$testfiles $testfile"
done

../runtest.py <(cat $testfiles) -- tclsh ../tcl/${step}_*
```

**Comment by kanaka** [comment]
I've added the functionality to the Makefile. Just set REGRESS=1. Like this:

```
make REGRESS=1 test^c^step4  # will use step2-4 test files
```

**Comment by dubek** [comment]
Awesome.

Can you mention it in README and process guide?

In process, maybe add at the end of each step:

```
make test^quux^step5
# After this passes OK, run regression test to verify nothing else was broken:
make REGRESS=1 test^quux^step5
```

**Comment by dubek** [comment]
There's a small bug with `REGRESS=1` -- the make command doesn't fail if an earlier step tests fail. For example:

```
make REGRESS=1 test^ruby^step4
# passes OK with exitcode 0

# edit tests/step3_env.mal and modify a test result to something else so test will fail
make REGRESS=1 test^ruby^step4
# passes OK with exitcode 0 <--- this should fail

make REGRESS=1 test^ruby^step3
# fails as expected
```
