### ISSUE TITLE
Testing commands fail in zsh

### ISSUE THREAD

**Issue by sleep** [kanaka/mal#113]
Love this project, finding it super pedagogical!

The guide mentions the shell command

`make test^quux^stepX`

to run tests.

This works fine in bash. It does not work in zsh, however. After an entire night and morning of thinking it was something wrong in my implementation code that prevented me from running the tests, I found out that zsh treats unquoted carets as globbing characters.

Perhaps you should change the guide to say

`make "test^quux^stepX"`

for sake of universality?

Or make a note that the args should be quoted, for zsh users?
Or make a note that the command should be prefixed with `noglob`, i.e.
`noglob make test^quux^stepX`, for zsh users?

**Comment by kanaka** [comment]
@sleep really sorry for the amount of time you spent figuring it out :-( although I'm glad you figured it out. I'm fine with either a note in the guide before the first test example or with quoting all the calls if that seems better. Would you like to send a PR with this change?
