### ISSUE TITLE
Fix nested equality tests and then make them mandatory

### ISSUE THREAD

**Issue by kanaka** [kanaka/mal#123]
The following implementations fail the soft tests for nested equality. Sequence nested tests in step4 and hash-map nested steps in step9:

- [x] bash (hash-map in hash-map)
- [x] elixir (seq in seq)
- [x] erlang (seq in seq)
- [x] factor (seq in seq)
- [x] forth (no native hash-map equality, see #116)
- [x] guile
- [x] haskell (seq in hash-map)
- [x] julia
- [x] kotlin (no native hash-map equality, see #116)
- [x] php (seq and hash-map in hash-map)
- [x] scala

Once those are all fixed we should make those tests mandatory.

**Comment by dubek** [comment]
Guile fix in #124.

**Comment by kanaka** [comment]
I'll work on julia

**Comment by kanaka** [comment]
I'll take scala too.

**Comment by kanaka** [comment]
Okay, julia and scala fixes pushed. Also, I added some nested hash-map tests in addition to the nested sequences tests.

**Comment by kanaka** [comment]
I updated the list with all the implementation that fail the new nested equality tests (including forth and kotlin which are missing hash-map equality entirely).

**Comment by kanaka** [comment]
Fix bash and PHP in: https://github.com/kanaka/mal/commit/33d33bb31bc3015548a3ad0d00fc33daf1cf827a (silly bugs really)

**Comment by kanaka** [comment]
Haskell was an easy fix too.

**Comment by ivern** [comment]
Kotlin should be updated to fixed now that it's merged.

**Comment by kanaka** [comment]
@jordanlewis @nlfiedler @ekmartin factor, erlang, and elixir and the only languages that still need this fix. Could you look at your respective implementation and fix the equality test when a sequence is embedded in another sequence? In other words, make these forms return true?

```
(= [(list)] (list []))
(= [1 2 (list 3 4 [5 6])] (list 1 2 [3 4 (list 5 6)]))
```

Thanks!

**Comment by jordanlewis** [comment]
Sure I will take a look at this.

**Comment by ekmartin** [comment]
Sure, I'll take a look.

**Comment by kanaka** [comment]
Just factor left now.

**Comment by kanaka** [comment]
@jordanlewis don't worry about factor since @dubek just fixed it.

**Comment by kanaka** [comment]
Final thing is making the tests not soft tests. I just pushed that and will close this once travis gives the green light: https://travis-ci.org/kanaka/mal/builds/106320895

**Comment by jordanlewis** [comment]
Thanks @dubek!

**Comment by kanaka** [comment]
All green. Closing.
