### ISSUE TITLE
Improving load-file to provide more feedback on errors

### ISSUE THREAD

**Issue by ktodyruik** [kanaka/mal#148]
I've been running the javascript MAL interpreter. I was wondering if anybody has written any alternative load-file functions that provide more feedback on errors.

**Comment by kanaka** [comment]
What sort of feedback are you looking for? In most implementation you should be able to do something like the following:

```
(try* (load-file "/etc/hosts") (catch* exc (prn "the exception was:" exc)))
```

That allows you to catch the string exception message and do what you want with it.

**Comment by ktodyruik** [comment]
Thanks for the reply. Honestly, when I wrote that question was just trying out mal for the first time and struggling a little. I misunderstood what I think was the browser caching my source for the interpreter swallowing the exception. I saw later that that was not the case. Thanks for the try catch example. I'll give that a try. :)
