### ISSUE TITLE
Extending language using the host language

### ISSUE THREAD

**Issue by ktodyruik** [kanaka/mal#149]
I'm using the javascript interpreter. What would be the best way to extend the interpreter by writing a new function in the host language (without modifying the original interpreter code)?

**Comment by kanaka** [comment]
Can you give a more concrete example of what you are trying to do?

**Comment by ktodyruik** [comment]
Sure. I noticed in some interpreters like biwa scheme, if you wanted to add a new function written in javascript, you would call something like this:
http://www.biwascheme.org./doc/internal/js_api.html

I was just wondering what would be the best way of adding my own native function to mal if I were to write one. Say, for example, I wrote
var alert = function(msg) {
   alert(msg);
};

What's the most straightforward way to add a new function to the interpreter?

Thanks

**Comment by kanaka** [comment]
Tracking JS interop fixes in #152
