### ISSUE TITLE
Javascript interop

### ISSUE THREAD

**Issue by ktodyruik** [kanaka/mal#152]
I was wondering what options are available for javascript (browser) interop in mal. Could you provide some examples of function execution and object property access?

Thanks!

**Comment by kanaka** [comment]
I changed the title slight to make this a more general bug. JS interop is completely broken at the moment. I'll hopefully be able to fix it this week and give some examples. I'm going to close #149 #150 and #151 since this encapsulates all of it.

**Comment by dubek** [comment]
Closing as this is solved via #221. Note that now the interop function is `js-eval` (instead of the older `js*`).
