### ISSUE TITLE
Add string manipulation capability

### ISSUE THREAD

**Issue by kanaka** [kanaka/mal#166]
Right now there is no cross-implementation way to manipulate (index, slice, etc).

In Clojure, strings are treated as sequences of characters and so sequence functions operate on them. However, as a simple initial (or maybe final) step, simply adding a *seq* function that turns a string into a list of single character strings would allow manipulation using normal sequence functions (*str* will already concatenate a sequence of character strings into a single string).

For now I'm thinking this would be an optional stepA function.

So here is the list for adding a *seq* function:

- [x] awk
- [x] bash
- [x] c
- [x] d
- [x] clojure
- [x] coffee
- [x] cpp
- [x] crystal
- [x] cs
- [x] erlang
- [x] elixir
- [x] es6
- [x] factor
- [x] forth
- [x] fsharp
- [x] go
- [x] groovy
- [x] guile
- [x] haskell
- [x] haxe
- [x] java
- [x] julia
- [x] js
- [x] kotlin
- [x] lua
- [x] make
- [x] mal
- [x] ocaml
- [x] matlab
- [x] miniMAL
- [x] nim
- [x] perl
- [x] php
- [x] ps
- [x] python
- [x] r
- [x] racket
- [x] rpython
- [x] ruby
- [x] rust
- [x] scala
- [x] swift
- [x] swift3
- [x] tcl
- [x] vb
- [x] vimscript

Also:

- [x] Update: process/stepA_mal.txt and process/guide.md

**Comment by kanaka** [comment]
I push several implementations to branch issue_166_string_ops.

**Comment by kanaka** [comment]
@dubek I've started implementing *seq* and *string?* on branch issue_166_string_ops. If you want to help, feel free to send PRs to this branch.

I'll probably do make and postscript next.

**Comment by kanaka** [comment]
@dubek btw, don't bother waiting for travis. Just send pulls against this branch and I'll merge it as soon as I see it. Any issues caught with travis can be dealt with later before this branch is merged onto the mainline.

**Comment by dubek** [comment]
Add a checkbox for process/stepA_mal.txt and process/guide.md updates.

**Comment by dubek** [comment]
tcl in #169. I'm working on vimscript and D and go.

**Comment by kanaka** [comment]
I'll take the "javas": groovy, java, scala.

**Comment by dubek** [comment]
I'll take the sharps: cs, fsharp, vb

And then crsyal, lua, perl.

**Comment by kanaka** [comment]
@dubek I discovered a bug in some implementations where (keyword? "") throws an error. I added a test in step9 and I'm just going to use travis to show which others still have the issue: https://travis-ci.org/kanaka/mal/builds/108816302

**Comment by dubek** [comment]
Thanks @kanaka, I just noticed myself that c-sharp has this bug.

**Comment by dubek** [comment]
@kanaka - Another thing I noticed (in ocaml, maybe others) is that `(symbol 'a)` and `(keyword :a)` don't just return the argument (idempotent), as they should (I believe).

**Comment by dubek** [comment]
I'll take guile and racket.

**Comment by dubek** [comment]
I'll try to tackle factor.

**Comment by kanaka** [comment]
@keith-rollin you around? Think you could tackle adding "string?" and "seq" to Swift? I don't have a system where I can do Swift development (although I may start poking at the Linux support for Swift at some point soon).

**Comment by kanaka** [comment]
After implementing Swift 3, I went ahead and updated Swift (2). It took a couple of rounds using Travis as a compile test, but it's working now. I'll let travis finish (https://travis-ci.org/kanaka/mal/builds/111649255) and then close this if there are no issues.
