### ISSUE TITLE
Mal [c] … user () … Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by igravious** [kanaka/mal#190]
The empty list causes the C version of Mal to fall over and die a screaming horrible death.

In the Ruby version a ```NoMethodError: undefined method `[]' for nil:NilClass``` exception is raised because in `return f[*el.drop(1)]` at the end of `EVAL` the variable `f` is `nil` (the non-existent first element of the list.

Is Mal meant to treat the empty list as both a List and Atom. If so, how?

Typing `()` into the online common Lisp interpreter http://learnlispthehardway.org/try-lisp/ gives the result `NIL`

**Comment by dubek** [comment]
Mal (like Clojure) has `nil` as a separate type/entity from the empty list.

Clojure treats `()` as the empty list, identical to `'()` or `(quote ())`. The last two work in Mal but simply `()` is treated as a function application and the function is not found (hence the exceptions/crashes).

Note that proper behaviour under bad input is not defined in Mal. For example, `+` need to arguments (e.g., `(+ 10 26)`), but it's undefined what will happen if you pass 0, 1 or 3 arguments to `+`.

**Comment by kanaka** [comment]
@igravious an unquoted empty list is a common enough issue that implementations shouldn't crash. So we'll fix any implementations that crash. In the general case though, @dubek is correct. It's perfectly acceptable for individual mal implementations to do rigorous error checking and useful error reporting, however, requiring that of all implementations is a non-goal. I know it's a little bit unusual, but the goal of mal is to support learning of both Lisp and other languages. Each implementation should run correct mal code the same way, but completeness and productization of the implementation is up to the implementor of each implementation.

I'll keep this issue open to fix empty list unrecoverable crashes.

**Comment by dubek** [comment]
I started fixing this in #194 . The travis status there will show how many more implementations need fixing.

**Comment by kanaka** [comment]
This should be resolved now.

**Comment by igravious** [comment]
Super. Mal has been a brilliant learning tool for me.
