### ISSUE TITLE
example from page 59 of TAPL not working quite as expected?

### ISSUE THREAD

**Issue by igravious** [kanaka/mal#193]
`user> (def! test (fn* [l m n] l m n))`

`user> (def! tru (fn* [t f] t))`

`user> (def! fls (fn* [t f] s))`

`user> (test tru 3 4)` should return `3`?
`user> (test fls 3 4)` should return `4`?

Instead I seem to get an unevaluated functions, either `#<Function: (fn* [t f] t)>` or `#<Function: (fn* [t f] f)>`

Thoughts?

**Comment by kanaka** [comment]
I think you have a couple of typos. You test function is missing some parens:

`(def! test (fn* [l m n] (l m n)))`

And your fls function has an incorrect variable name:

`(def! fls (fn* [t f] f))`

Making those changes I get the correct behavior.

**Comment by igravious** [comment]
Fixed my typo up above. Thx

Oh, do I need `()` around multiple variables?

**Comment by kanaka** [comment]
Parens in Lisp define lists. However, when an unquoted list is evaluated in Lisp, the first position in the list is a function and the rest of the elements are arguments. So `(+ 2 3)` means call the `+` function using the arguments 2 and 3. In mal, `(fn* (a b) (+ a b))` means define an anonymous function that takes two arguments and calls `+` using those arguments. This `(fn* (a b) + a b)` is quite different. That's an anonymous function containing three elements that are not in a list. Mal only uses the first element in the function body so it's really equivalent to this: `(fn* (a b) +)`. When you invoke/apply that function you'll just get what `+` evaluates to. In other words, this `( (fn* (a b) +) 7 8)` will invoke/apply the anonymous function, the `+` symbol will be evaluated to the native function for addition which will be returned.

It's late at night and I'm tired, so the above explanation might be a bit rambling, let me know if it doesn't make sense and I'll try and give a better answer tomorrow after some sleep.
