### ISSUE TITLE
Trying to write filter function

### ISSUE THREAD

**Issue by ktodyruik** [kanaka/mal#234]
Hi,

I'm trying to write a filter function. I've tried a couple attempts and I am getting some odd results. Would appreciate some feedback as to what I am doing wrong.

```
(def! zero? (fn* (n) (= 0 n)))

(def! car first)

(def! cdr rest)

(def! filter
  (fn* (pred xs)
    (if (> (count xs) 0)
	  (if (pred (car xs)) 
		(cons (car xs) (filter pred (cdr xs)))
		(filter pred (cdr xs)) 
	  '() 
	))))
```

And then in the js repl I'm getting:

```
> (filter zero? '(0 1 2 3))
(0 nil)
```

Thanks

**Comment by kanaka** [comment]
@ktodyruik heh, your code indenting is misleading you. This line:

```(filter pred (cdr xs))``` should actually be 
```(filter pred (cdr xs)))```
(and then of course you need one less paren at the end)

If you use vim, @dubek has a very helpful vim plugin for mal: https://github.com/dubek/vim-mal I was able to reformat your code with it and immediately saw the problem based on the indenting.

**Comment by ktodyruik** [comment]
Thanks, Joel! I didn't know about the Vim plugin. That's a great tip. Love Vim!
Kerry
