### ISSUE TITLE
Threading macro question

### ISSUE THREAD

**Issue by ktodyruik** [kanaka/mal#235]
I was trying out the -> operator that is in core.mal.

How would you use functions like map or filter with ->? Leaving off the argument doesn't automatically create a partially applied function and return another function. I could create an anonymous function or create a new function. Is there a more general way to do partial function application on map or filter so that I can use it in ->?

Thanks,
Kerry

**Comment by kanaka** [comment]
Can you give a code example of what you are trying to do?

**Comment by ktodyruik** [comment]
Yup.

For example,

```
(def! people '({"Name" "Homer" "Age" "43"} {"Name" "Bart" "Age" "8"}))

; This is easy and works. I would like to try rewriting it using ->
(map (fn* (p) (get p "Name")) people)
```

```
; This doesn't work as I don't think the map will return a partially applied function. Some languages do this automatically.
(-> people
      (map (fn* (p) (get p "Name")))

; I could write a new function
(def! map-people (fn* (people) (map (fn* (p) (get p "Name")) people)))

; Then apply it like this and it works
(-> people map-people)

; I could try an anonymous function. But there must be an error here as I can't get this to work.
(-> people (fn* (ppl) (map (fn* (p) (get p "Name")) ppl)))
```

Is there a better way of rewriting my original map in the first example using ->?

**Comment by wasamasa** [comment]
Threading macros and lambdas don't mix terribly well.  In the case of `map`, it's common to see `->>` for cleaning up an unwieldy expression the anonymous function is applied to.  One can also mix both when needed.

**Comment by ktodyruik** [comment]
@wasamasa Thanks. I think I was misunderstanding the difference before thread first and last and confusing what was going wrong with my expression. I thought it had something to do with partial function application. I see now that I was just using the wrong threading macro.

Here is my working code:

```
(def! people '({"Name" "Homer" "Age" "43"} {"Name" "Bart" "Age" "8"}))

; This is easy and works. I would like to try rewriting it using ->
(map (fn* (p) (get p "Name")) people)

; Here it is rewritten (works now)
(->> people 
     (map (fn* (p) (get p "Name"))))

; I wanted to chain filter and map together so I did that next
(->> people 
     (filter (fn* (p) (eq? (get p "Age") "43")))
     (map (fn* (p) (get p "Name"))))	 
```

Thanks for your help. 
Kerry
