### ISSUE TITLE
Useful functions

### ISSUE THREAD

**Issue by ktodyruik** [kanaka/mal#236]
I was wondering what useful functions people have written (in mal) to supplement the base mal language. I noticed some functions and macros in core.mal with some useful functions. I like the clojure-style threading macros. Very clever and shows what a capable language mal is. I didn't see filter in the git repository so I wrote my own the other day and was going to write 'range' next. Are there any other sources of supplemental functions/macros written in the core mal language that I am missing? Could anybody share what useful functions they have written? I'd be very interested in seeing what clever things people have written, what functions they have implemented, and how they implemented them.

@kanaka Joel, if it doesn't exist already, what do you think about a place for user contributed functions?

-Kerry

**Comment by dubek** [comment]
Look at the `examples` subdir for some, well, examples, like Clojure-like protocols.

For a bunch of more Mal code (like a Mal tokenizer and parser) you can look at my [malc repository](https://github.com/dubek/malc), though I can't recommend specific reusable functions on top of my head.

@kanaka and I previously discussed adding a `lib` subdir with `core.mal` and a bunch of other stuff (even move `tokenizer.mal` from malc). It hasn't happened (yet).

**Comment by kanaka** [comment]
@ktodyruik yes, please feel free to send pull requests that add useful functions to the `examples/` subdir. At some point, we'll re-organize to move more lib/contrib related stuff to a separate directory. If you include a test file in the same directory for now (and using the standard format), that would be great too.

**Comment by kanaka** [comment]
@ktodyruik also a lot of Clojure functions and macros should port to mal fairly easily as long as they don't rely on protocols or lazy sequences. The semantics and data structures in mal are modeled after Clojure.

**Comment by ktodyruik** [comment]
@kanaka Could you elaborate on what you meant by "If you include a test file in the same directory for now (and using the standard format), that would be great too." Thanks.

**Comment by kanaka** [comment]
The test syntax I'm referring to is that used in `tests/*`. And you can run `runtest.py` directly to run mal tests. For example, consider you defined a `sumdown` function in `examples/sumdown.mal`:

```clojure
(def! sumdown (fn* (N) (if (> N 0) (+ N (sumdown  (- N 1))) 0)))
```

The you could define a test file `test_sumdown.mal` like this:
```clojure
(load-file "sumdown.mal")

(sumdown 0)
;=>0
(sumdown 1)
;=>1
(sumdown 5)
;=>15
```

You can now run those tests using a specific implementation like this:

```bash
mal/examples $ ../runtest.py test_sumdown.mal ../js/run
Started with:
Mal [javascript]

TEST: (load-file "sumdown.mal") -> ['',*] -> SUCCESS
TEST: (sumdown 0) -> ['',0] -> SUCCESS
TEST: (sumdown 1) -> ['',1] -> SUCCESS
TEST: (sumdown 5) -> ['',15] -> SUCCESS

TEST RESULTS (for test_sumdown.mal):
    0: soft failing tests
    0: failing tests
    4: passing tests
    4: total tests
```
