### ISSUE TITLE
Unable to get test harness working with node

### ISSUE THREAD

**Issue by cowboyd** [kanaka/mal#259]
First, a little background. I had been trying to do a MAL implementation in web assembly, but when I wasn't progressing fast enough I thought, well how can I cut scope... Rather than learning to make a lisp AND learn WASM at the same time, let me do one and then the other. 

Soooooo. I decided to tackle the first issue first, and I'm going to try doing it with `node.js`. However, I sat down to get `step0` working, but had a problem with the test harness. I can't seem to get it to pass, even though it works IRL.

You can see my implementation here https://github.com/cowboyd/mal/blob/mal-node/node/step0_repl.js

And also the output from the test harness, and IRL https://gist.github.com/cowboyd/b481f8e9851df8403145a4857e20f429

If I turn on the `--debug-file` and `--log-file` this is the output.

https://gist.github.com/cowboyd/08f634dfe1042fdb7f696798d7931feb

Also, an GIF showing the progression:

![2017-05-20 15 31 26](https://cloud.githubusercontent.com/assets/4205/26279182/3b9e7004-3d72-11e7-9783-1c05332fe313.gif)

I'm using the Node.js `readline` library which might have something to do with it. It looks as though there are some control characters being output with the prompt. Should the test harness handle that?

**Comment by kanaka** [comment]
I think first working on a Lisp in a dynamic language you know well is a good strategy. I suspect you are running into this problem: https://github.com/kanaka/mal/issues/258#issuecomment-299007084

**Comment by kanaka** [comment]
BTW, what tool do you use to do the terminal recording?

**Comment by cowboyd** [comment]
Yup, that was it. I'd actuall gotten it to work by not using the nodejs `prompt()` method which reports a new line of intput in a non-standard way.

```
TEST RESULTS (for ../tests/step0_repl.mal):
    0: soft failing tests
    0: failing tests
    4: passing tests
    4: total tests
```

fwiw, I use Gifox. It's pretty great http://gifox.io/

**Comment by cowboyd** [comment]
Closing this since the suggestion fixed the issue. I just checked for the `MAL_IMPL` environment variable to set the `terminal: false`

Thanks!

https://github.com/cowboyd/mal/blob/mal-node/node/step0_repl.js#L25-L29
