### ISSUE TITLE
Why a mal function needs the function in step 5 (TCO)?

### ISSUE THREAD

**Issue by asterite** [kanaka/mal#27]
It says:

```
The return value from the fn* special form will now become an object/structure
with attributes that allow the default invoke case of EVAL to do TCO
on mal functions. Those attributes are:

fn: the original function value return in step 4
...
```

But I don't see where that original function is used, anywhere.

Is that a mistake or is there something I'm overlooking?

**Comment by kanaka** [comment]
Yeah, that's because I haven't written most of step9 in the guide yet. You won't need it until you try and implement the map and apply core functions. Then you'll be happy you did because you can just extract the function and run it. In OOP languages, I've done this via an apply method on the malfunc object, but you still either need the original function or a reference to EVAL stored in the object.

I should really clarify that storing the original function is optional until step 9.

Does that help?

**Comment by kanaka** [comment]
Crystal eh? I think that's the first time I've heard of it. Looks interesting.

**Comment by asterite** [comment]
Oh, I see! I'm in step 6 right now, and I searched in the guide to see if that `fn` was mentioned elsewhere. Thanks for the clarification, I won't remove it then :-)

Crystal is pretty new, maybe that's why it's not on that page. Thanks to your guide I was able to find a couple of bugs in the compiler, mostly because of the need to use function pointers and closures. 

Thank you so much for this project! It's really fun, and before this I didn't know much about lisp and didn't like it that much because of the many parenthesis, but I'm now able to see its simplicity and power, like, just a few lines added in each step and the language becomes more and more powerful. It's really hard to imagine that all of this started around the sixties!!

**Comment by kanaka** [comment]
Awesome! That's exactly the sort of experience I was hoping people would get from it.

And yes, apart from the homoiconic nature of Lisp syntax, the very structured syntax means that reading (lexing/parsing) and printing are nearly trivial compared to other languages. Reading and writing it as a human takes a while to get used to, but if you have a decent editor syntax that does syntax highlighting, parenthesis matching, and proper indenting, you start to not see the parenthesis after a while.

**Comment by kanaka** [comment]
Oh, I forgot to mention. Feel free to join #mal (freenode). Some of the other contributors/implementors of mal hang out there.

**Comment by kanaka** [comment]
I noted in the guide that this is deferrable until step 9.
