### ISSUE TITLE
Scheme2mal

### ISSUE THREAD

**Issue by zaoqi** [kanaka/mal#283]

**Comment by zaoqi** [comment]
@wasamasa Scheme/Racket2mal: https://github.com/zaoqi/scheme.mal

**Comment by kanaka** [comment]
@zaoqi If you would like to get this code into the mal repo, I think it would be interesting under examples/. A bit more documentation in the file or perhaps by adding a `examples/README.md` would be useful (motivation, usage, etc). Also, the preferred license for mal code and examples is MPL 2.0.
