### ISSUE TITLE
lua

### ISSUE THREAD

**Issue by zaoqi** [kanaka/mal#286]
Some Lua interpreter doesn't support `require`(e.g. minetest https://github.com/minetest/minetest/).
Use `dofile`

**Comment by wasamasa** [comment]
I doubt the Lua interpreter embedded in Minetest would work with the current implementation:

> Running the Lua implementation of mal requires lua 5.1 or later, luarocks and the lua-rex-pcre library installed.

**Comment by zaoqi** [comment]
@wasamasa Minetest doesn't support `require`. because of safe

**Comment by kanaka** [comment]
@zaoqi if you would like to submit a pull request that add support for the Minetest Lua without breaking the current lua support we would consider it. Please make sure to include a way to automatically test it with the Minetest Lua (i.e. a lua_MODE setting like scheme_MODE or haxe_MODE) and updates to the lua Dockerfile to install Minetest lua alongside the regular lua.
