### ISSUE TITLE
call stack

### ISSUE THREAD

**Issue by zaoqi** [kanaka/mal#287]

**Comment by wasamasa** [comment]
Please don't open issues without any description whatsoever.  I have absolutely no idea what your intention is and am inclined to just close this issue.

**Comment by zaoqi** [comment]
I wan to get call stack when error

**Comment by kanaka** [comment]
@zaoqi it's still not clear what you're asking for. Most implementations already display a call stack when they encounter an uncaught error (some of the ahead-of-time compiled implementations don't have call stacks). You're welcome to submit a pull request adding call stacks to implementations that don't have them.

Perhaps you mean a mal call stack when using an implementation to run another mal program? That's an interesting feature, but that would require changing all 69 implementations. I'm fine if individual implementation implement this feature, but I'm not going to add this as a mandatory part of the incremental steps. It would need to be a follow-on to step A functionality.

Another possible meaning of "get call stack" is that the try*/catch* form captures the call stack as an attribute of the exception that is accessible to mal programs. Again though, this would be per implementation and would not make sense as part of the standard steps. Note that mal implementations in the repository are intended for educational purposes and not for production. You're welcome to take any specific implementation and add features that make them more production ready (as long as you honor the code license of course).
