### ISSUE TITLE
Bound

### ISSUE THREAD

**Issue by zaoqi-unsafe** [kanaka/mal#302]
Add
*int-max-bound*  integer or false
*int-min-bound*
*integer*  Scheme Racket Haskell:Integer true other false
*ratio* boolean
*float* boolean

**Comment by wasamasa** [comment]
I vote for no here.  If you plan on implementing Scheme's numeric tower, forget about it.  The tests specify so far that you can use integers, including negative numbers.  Requiring any more than that is unreasonable, I feel the same about introspection, including but not limited to the limits and types of numbers of the implementation.

**Comment by kanaka** [comment]
This is interesting, but not for the core learning/guide purpose of mal. Many of these are very complicated to implement depending on the underlying target language. And they don't add to the core goal of learning Lisp and/or a target language. This would be more interesting as a blog post about how you might add this to an existing mal implementation, but it's not going to be added to the basic guide or to all the implementations.

**Comment by zaoqi** [comment]
@wasamasa JS implementation doesn't support integer like Haskell Integer.

**Comment by wasamasa** [comment]
@zaoqi This is irrelevant as it's an implementation detail. If the implementation passes the tests where two integers are added, it's fine for our purpose.
