### ISSUE TITLE
Shen

### ISSUE THREAD

**Issue by zaoqi** [kanaka/mal#303]

**Comment by wasamasa** [comment]
If you want a Shen implementation, make one and open a pull request.

**Comment by zaoqi** [comment]
@wasamasa https://github.com/kanaka/mal/tree/shen

**Comment by wasamasa** [comment]
The description field is there for a reason, if you don't say what you want, don't expect me to help you.

**Comment by kanaka** [comment]
@zaoqi I started that Shen branch a while ago. I would be happy to take a pull request with a full Shen implementation, however, I won't be able to implement it in the near future. If you are interested in a Shen implementation, feel free to implement it and send a pull request.

**Comment by iqbalansari** [comment]
FYI I am working on an [implementation](https://github.com/iqbalansari/mal/tree/shen2/shen) in Shen, it is almost complete (3 steps remaining)

**Comment by kanaka** [comment]
@iqbalansari awesome! Thanks for letting us know.

**Comment by dubek** [comment]
@iqbalansari Cool! After that will be done, when can we expect a Shen port running in Mal? :-)

**Comment by wasamasa** [comment]
@iqbalansari Very nice.
