### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by zaoqi-unsafe** [kanaka/mal#304]
zh_CN https://github.com/Windfarer/mal-zh

**Comment by kanaka** [comment]
@zaoqi-unsafe it's not clear what you are asking. Are you wanting a link to this in the README? Are you wanting this translation included side-by-side with the English guide (I would probably only do that if the author of the translation is willing to commit to keeping it up to date with the English version). A link is fine idea, but please submit a pull request with the change you would like to see. Thanks.
