### ISSUE TITLE
Scheme

### ISSUE THREAD

**Issue by zaoqi-unsafe** [kanaka/mal#305]
Lots of scheme implementions don't support library, `case` and `when`.

**Comment by kanaka** [comment]
@zaoqi-unsafe I'm not sure what you are asking. `case` and `when` are not in the scope of mal. However, you can implement them using macros in mal. If you implement macros for them, please add them under `examples/` and submit a pull request. I would be happy to add them there if you implement them and send a good PR.

**Comment by wasamasa** [comment]
I'll just assume you refer to the Scheme code of the MAL implementation using when, define-library and more. This is intentional as it targets the R7RS standard (see the README) which provides all necessary features for implementing MAL. I therefore consider this suggestion invalid.
