### ISSUE TITLE
Another Rust Implemention

### ISSUE THREAD

**Issue by seven1m** [kanaka/mal#327]
I finished my own Rust implementation of Mal recently. I don't think mine is any better than the implementation in this repo, but I would appreciate a link from your readme, if you think that is appropriate!

https://github.com/seven1m/mal-rust

**Comment by kanaka** [comment]
Was just working through my emails and realized I had never followed up on this. I have added a link to your implementation in the README.

**Comment by seven1m** [comment]
Yay, thank you!!
