### ISSUE TITLE
Undefined behavior and test case improvements

### ISSUE THREAD

**Issue by rbobrowicz** [kanaka/mal#332]
Not sure how active this repository is anymore, but I just started going through the process and finished step 1. All the test cases pass, but I still tried to compare my implementation to existing ones to make sure I didn't miss anything. I noticed a few inconsistencies right off the bat.

## Multiple expressions
I realized after I was done that my implementation was throwing away all user input after the first parsed expression. I thought this was a bug at first, but it turns out other implementations are doing the same thing.

```
user> (one two) this does not matter
(one two)
```

Throwing away all user input after the first expression seems wrong, but at least the clojure, bash and python implementations all do it as well. Real lisps have no problems with multiple expressions:

```
Clojure 1.9.0
user=> (+ 1 2) (+ 3 4)
3
7
```

Changing the required behavior at this point might be too much since it is likely to break a lot (all?) implementations, but maybe it can be added as an optional enhancement.

## Signed Integers
There is a test for `-1`, but there is no test case for `+1`. Clojure implementation parses that as a positive 1, while python parses it as a symbol `+1`.

```
#clojure impl
user> +1
1
#python impl
user> +1
+1
```

The clojure behavior is IMO the correct one here since most languages (including Clojure and Common Lisp) allow optional signs in front of numbers. Perhaps this should be added as a test case.

## Numbers with trailing signs
I noticed my implementation was breaking up `1+` into two tokens:

```
user> (1+ 2)
(1 + 2)
```

Which I'm pretty sure is the wrong thing to do, but I couldn't find consensus as to what the right thing is. Clojure and MAL implemented in clojure both throw parse errors, while python parses it as the symbol `1+`, which is what Common Lisp does (where `1+` is actually the increment function). Not really sure what the right answer here is.

## Reader macro characters within symbols
I wasn't sure if macro characters can appears within symbols, ie are they only macro characters at the start of forms. Clojure behaves as follows:

```
user=> '(1'1)
(1 (quote 1))
user=> '(1`1)
(1 1)
user=> '(1~1)
(1 (clojure.core/unquote 1))
user=> '(1~@1)
(1 (clojure.core/unquote-splicing 1))
user=> '(1@1)
(1 (clojure.core/deref 1))
user=> '(x'x)
(x'x)
user=> '(x`x)
(x (quote user/x))
user=> '(x~x)
(x (clojure.core/unquote x))
user=> '(x~@x)
(x (clojure.core/unquote-splicing x))
user=> '(x@x)
(x (clojure.core/deref x))
```

So, numbers separated by a quote are broken up, but `x'x` gets parsed as whole symbol. The only real surprise was the difference between (1\`1) => (1 1) and (x\`x) => (x (quote user/x)). Not sure why clojure eats the quote in the first case.

MAL implemented in Clojure behaves similarly, just with more consistent quasiquote handling:

```
user> (1'1)
(1 (quote 1))
user> (1`1)
(1 (quasiquote 1))
user> (1~1)
(1 (unquote 1))
user> (1~@1)
(1 (splice-unquote 1))
user> (1@1)
(1 (deref 1))
user> (x'x)
(x'x)
user> (x`x)
(x (quasiquote x))
user> (x~x)
(x (unquote x))
user> (x~@x)
(x (splice-unquote x))
user> (x@x)
(x (deref x))
```

I believe this is the intended behavior. In comparison the python implementation is pretty bugged:

```
user> (1'1)
(1 (quote 1))
user> (1`1)
(1 (quasiquote 1))
user> (1~1)
(1~1)
user> (1~@1)
(1~ (deref 1))
user> (1@1)
(1 (deref 1))
user> (x'x)
(x (quote x))
user> (x`x)
(x (quasiquote x))
user> (x~x)
(x~x)
user> (x~@x)
(x~ (deref x))
user> (x@x)
(x (deref x))
```

`x'x` is not allowed as a valid symbol and the splice and unquote-splice are totally mishandled. These should be pretty straight forward test cases to add.

**Comment by wasamasa** [comment]
Hello there. I'm just a contributor of a few implementations, so don't take the things below as an absolute decision, more of a set of observations I've made over time with this project.

Generally speaking I doubt most of the changes to interpreter behavior you've proposed are worth doing. Consider that this repository is concerned with teaching people how to implement a Lisp interpreter, not to implement the best Lisp interpreter in existence. Interpreting an omission like how trailing input is handled liberally (like by ignoring it) is fine as it doesn't impact the learning experience. Interpreting it differently is fine, too. Mandating a specific behavior that doesn't help with that overall goal is lots of effort for little gain.

There is one important exception though, if you've run into a missing test case that would have saved you from much pain while developing, please consider contributing it. This becomes crucial for the self-hosting step as failures in it are far harder to debug.

**Comment by rbobrowicz** [comment]
Hi,

What you are saying makes sense, and in light of that I can see how most of my suggestions don't further the goals of the project. Although if I may play devil's advocate for a moment. By ignoring trailing input there was at least one bug that the test suite was not able to properly test for. I had accidentally made my line comment prefix `;;` instead of a single `;`. The test case `1; a comment` passed precisely because after parsing the first expression (`1`) the interpreter stopped and never actually tested the comment parsing. Not sure if that qualifies, but I thought I'd mention it.

Looking at other test cases I added to my fork the only other one that might fit your criteria is a test case for `(abc,def) => (abc def)`. The current comma handling tests use numbers only and my parser was tokenizing numbers correctly, but accidentally globbed the comma as part of a symbol name. This was the bug that set me off to see how other characters should be handled inside symbols, like quote, quasiquote, splice...etc.

**Comment by kanaka** [comment]
I'm going to go ahead and close this issue. @rbobrowicz if you're still interested, you can submit a pull request for the comma parsing, that will trigger travis to run for that PR and give a list of implementations with the problem.
