### ISSUE TITLE
New Implementation in C (Compiled)

### ISSUE THREAD

**Issue by seven1m** [kanaka/mal#342]
I have just finished malcc and published it here: https://git.sr.ht/~tim/malcc

**malcc** is an incremental compiler for Mal and blazing fast. I'd appreciate a link in your readme!

**Comment by kanaka** [comment]
Done. Cool stuff!

Now that I have you here, any chance you want to tackle a rewrite of the C interpreter? It's one of the implementations that I did early on and to be quite frank, it's not very good. As I recall it doesn't even compiles any more with updated dependencies. It's not particularly idiomatic C code, it relies on glib (it would be better if it didn't) and uses Boehm for GC (ref counting, more direct GC, or even just more direct use of Boehm would be better). I would be happily replace my C implementation with a better one. Any interest? You might even be able to start from your compiler and de-evolve it to an interpreter.

**Comment by seven1m** [comment]
Thanks for the quick update!

Yeah! I'd love to rewrite the C implementation. I'll see about "de-evolving" (love that) malcc into an interpreter.

**Comment by kanaka** [comment]
@seven1m awesome! I look forward to it.
