### ISSUE TITLE
arithmetic operations

### ISSUE THREAD

**Issue by 00003481** [kanaka/mal#346]
the arithmetic operators +,-,*,/ are parsed well 
but they are computed only as dyadic operators

quite a few implementations suffer of the same disease :-) 

the included changes fix the problem for rexx
and makes them behave more according to the lisp standards

mal_add: procedure expose values. /* mal_add(...) */
    res = 0
    do  i = 1 to arg()
        res += obj_val(arg(i))
    end
    return new_number(res)

mal_sub: procedure expose values. /* mal_sub(...) */
    if arg() = 0 then ,
        return new_nil()
    if arg() = 1 then do
        return new_number(-obj_val(arg(1)))
    end
    res = obj_val(arg(1))
    do  i = 2 to arg()
        res -= obj_val(arg(i))
    end
    return new_number(res)

mal_mul: procedure expose values. /* mal_mul(...) */
    res = 1
    do  i = 1 to arg()
        res *= obj_val(arg(i))
    end
    return new_number(res)

mal_div: procedure expose values. /* mal_div(...) */
    if arg() = 0 then ,
        return new_nil()
    if arg() = 1 then ,
        return new_number(1/obj_val(arg(1)))
    res = obj_val(arg(1))
    do  i = 2 to arg()
        res /= obj_val(arg(i))
    end
    return new_number(res)

numbers expressed as fractions and providing the result of divisions as proper fractions 
is still not supported, but I am dealing with it

**Comment by kanaka** [comment]
@00003481 I don't object to individual implementations supporting variadic arithmetic operations, but it's intentionally not a testing or language requirement. It's actually fairly straight forwards to use a macros to define variadic arithmetic operators using the two argument versions (the and and or macros effectively do the same thing). And one advantage is that all 75 implementations could use those macros.

However, if you want to support variadic arithmetic operations directly in an implementation I'm happy to consider pull requests. I'm going to close this ticket, but if you would like to get this change in, please submit a pull request (this will trigger Travis to test the change and you will get proper credit for the change).
