### ISSUE TITLE
Cheatsheet link in guide.md is broken

### ISSUE THREAD

**Issue by sesm** [kanaka/mal#349]
Cheatsheet link in `guide.md` points to http://kanaka.github.io/mal/process/cheatsheet.html, which returns 404.

**Comment by kanaka** [comment]
@sesm thanks for the catch. I've corrected that link. I also noticed that the language popularity link was to a site that hasn't existed in a while so I replaced it with a couple different sites (RedMonk and GitHut 2.0).
