### ISSUE TITLE
Fix handling of empty list

### ISSUE THREAD

**Issue by kanaka** [kanaka/mal#364]
Commit https://github.com/kanaka/mal/commit/64c11d81a0735a2d7603770a8fd407c80fae6491 introduced a better way of testing nth by avoiding vectors which are deferrable. However, in the process it revealed that not all implementations are correctly handling empty lists once macros are introduced (the first test of empty list is in step2 and we don't test again in step 8).

The following implementations were affected by the empty list `()` bug:

- [x] crystal
- [x] java
- [ ] nasm
- [X] rpython
- [X] rust
- [X] swift4
- [X] ts

**Comment by kanaka** [comment]
Travis run https://travis-ci.org/kanaka/mal/builds/529508205 is most recent test run to include this additional test plus some of the fixes.

**Comment by kanaka** [comment]
@bendudson Any chance you could look at fixing nasm? I tried copy the trivial empty_list test from step2 to later steps but quickly ran into some issues. Basically the problem is that the eval function needs to check to see if the ast is an empty list prior to macro expansion (in addition to after) and if it's empty return the empty list (without trying to apply it).

**Comment by bendudson** [comment]
Yes no problem. It may be a few days before I can get to this though.

**Comment by kanaka** [comment]
@bendudson I figured out what I was doing wrong (step5 onwards requires `jmp .return` and not just `ret` from the `.empty_list` routine). The change now passed all the tests. When you can a chance can you review it just to make sure I didn't get something subtle wrong: https://github.com/kanaka/mal/commit/7f5a3db0c658d07595d1b21c9974943044750f80

**Comment by bendudson** [comment]
Thanks @kanaka that looks good. Sorry I didn't get to it earlier.
