### ISSUE TITLE
[C] Cannot pass USE_GC to make via command line

### ISSUE THREAD

**Issue by junjiemars** [kanaka/mal#395]
In C implementations (```mal/c```), can not passing USE_GC through the command line to ```make```.

**Comment by junjiemars** [comment]
[#395](https://github.com/junjiemars/mal/commit/1001b3e05c30898a557d0ae69a924251b9f2ba76)

**Comment by kanaka** [comment]
Can you give me a brief rationale for what this enables?

**Comment by junjiemars** [comment]
```libgc-dev``` is not a standard C library, under the ```mal/c``` directory, 
```sh
make clean step0_repl
```
the ```gc/gc.h file no found``` compiler error should occurred.
If ```USE_GC``` can be passed via command line, such as
```sh
make clean step_0_repl USE_GC=
```
I can avoid the compiler error on some box there no ```libgc-dev``` installed.

```USE_GC``` as a feature macro already coded correctly in source code except the ```mal/c/Makefile```:

```diff
modified   c/Makefile
@@ -28,12 +28,12 @@ ifeq (,$(USE_READLINE))
 RL_LIBRARY ?= edit
 else
 RL_LIBRARY ?= readline
-CFLAGS += -DUSE_READLINE=1
+CFLAGS += -DUSE_READLINE=$(USE_READLINE)
 endif
 
 ifeq (,$(USE_GC))
 else
-CFLAGS += -DUSE_GC=1
+CFLAGS += -DUSE_GC=$(USE_GC)
 LDFLAGS += -lgc
 endif
```
 
So I make the fix in [#395](https://github.com/junjiemars/mal/commit/1001b3e05c30898a557d0ae69a924251b9f2ba76).

**Comment by kanaka** [comment]
You don't need the patch to disable gc. If you run `make USE_GC= step0_repl` it will build without gc even without the patch. Please show the problem that is happening without the patch that you are trying to fix. I.e. the full before and after that you see.

**Comment by junjiemars** [comment]
In mal/c/Makefile, the using USE_GC is hard coded, so it cannot be build with USE_GC=

**Comment by junjiemars** [comment]
Indeed, USE_READLINE has the same issue with USE_GC.

**Comment by kanaka** [comment]
It's not hard-coded. The purpose of '?=' is to provide an overridable default. For example, consider the following simple `Makefile.example`:

```
USE_GC ?= 1
$(warning USE_GC: '${USE_GC}')
all:
```

Here is how that can be used:

```
$ make -f Makefile.example 
Makefile.example:3: USE_GC='1'
make: Nothing to be done for 'all'.
$ make -f Makefile.example USE_GC=
Makefile.example:3: USE_GC=''
make: Nothing to be done for 'all'.
```

Notice that USE_GC has a value of 1 when no other command line arguments are specified. When `USE_GC=` is used, then USE_GC no longer has a value.

I'm going to close this issue and the pull request. If you still believe there is an issue, please give a more detailed explanation of what you are trying to do. In particular, please show both the commands you are trying to run and what the result is in the broken case.

**Comment by junjiemars** [comment]
Did you see CFLAGS?

**Comment by kanaka** [comment]
The CFLAGS setting is protected by an `ifeq` so CFLAGS will only have `-DUSE_GC=1` if USE_GC is set to something non-blank.

Expanded example:

```
USE_GC ?= 1

ifeq (,$(USE_GC))
else
CFLAGS += -DUSE_GC=1
endif


$(warning USE_GC='${USE_GC}', CFLAGS='${CFLAGS}')

all:
```

```
$ make -f Makefile.example 
Makefile.example:9: USE_GC='1', CFLAGS='-DUSE_GC=1'
make: Nothing to be done for 'all'.
$ make -f Makefile.example USE_GC=
Makefile.example:9: USE_GC='', CFLAGS=''
make: Nothing to be done for 'all'.
```

**Comment by kanaka** [comment]
Again, please show me an actual example of the trouble you are seeing not just a description of what you think is going on.

**Comment by junjiemars** [comment]
Hi, @kanaka , you are right, there are a ```ifeq``` above the code.
