### ISSUE TITLE
Nasm fails on zero argument function call after step4

### ISSUE THREAD

**Issue by kanaka** [kanaka/mal#429]
This was discussed in https://github.com/kanaka/mal/pull/426 but since that issue is unrelated and already closed I'm opening this to track the issue.

The following succeeds in nasm step4 but fails in step5-A:

```
( (fn* () 4) )
```

@bendudson, can you take a look at this? Thanks.

**Comment by bendudson** [comment]
I've had a look and can't see yet where the problem is, but am getting close (I think). The following works, for example:
```
(def! f (fn* () 4))
(f)
```
I think something is being freed which shouldn't be (connected to the TCO optimisation), with maybe another bug complicating things. I'll try to work this out soon.

**Comment by kanaka** [comment]
@bendudson thanks. That's sounds plausible. And yeah the interaction between TCO and GC is definitely a pain.

**Comment by kanaka** [comment]
Resolved by #433
