### ISSUE TITLE
Drop PHP 5.x version supports

### ISSUE THREAD

**Issue by peter279k** [kanaka/mal#434]
As title, the PHP version of mal still supports the `php-5.3` versions.

And using the old Ubuntu distribution version.

IMHO, I think we can consider following enhancement works:

- Drop the older `php-5.x` version supports since the `php-7.x` versions have been released for whiles.
- Enhance the `Dockerfile` in `php` folder, let the Ubuntu distribution be the currently supported version.

Once this issue is accepted, I can work on this and create related PR :).

**Comment by kanaka** [comment]
That's fine. Are you planning on updating the implementation to support newer features of 7.x or are you just going to update the Dockerfile?

**Comment by peter279k** [comment]
Hi @kanaka, thanks for your reply.

If possible, these two works you mention I can resolve them :).

**Comment by kanaka** [comment]
Dockerfile has been update to ubuntu:20.04 which updates PHP version to 7.4.3
