### ISSUE TITLE
./.travis_test.sh failing on ada.2

### ISSUE THREAD

**Issue by epylar** [kanaka/mal#456]
When I run `./.travis_test.sh ada`, I'm able to run the `ada` tests.

When I run: `./.travis_test.sh ada.2`, I get an error:

```
+ ACTION=test
+ IMPL=ada.2
+ BUILD_IMPL=ada.2
+ TEST_OPTS=' --debug-file ../test.err'
+ '[' '' ']'
+ '[' '' ']'
+ echo 'ACTION: test'
ACTION: test
+ echo 'IMPL: ada.2'
IMPL: ada.2
+ echo 'BUILD_IMPL: ada.2'
BUILD_IMPL: ada.2
+ echo 'MAL_IMPL: '
MAL_IMPL: 
+ '[' '' -a test = perf ']'
+ '[' '' -a '' ']'
+ '[' '' -a '' -a test = perf ']'
+ mode_var=ada.2_MODE
./.travis_test.sh: line 39: ada.2_MODE: invalid variable name
```

The trace for testing `ada` looks like this:

```
+ ACTION=test
+ IMPL=ada
+ BUILD_IMPL=ada
+ TEST_OPTS=' --debug-file ../test.err'
+ '[' '' ']'
+ '[' '' ']'
+ echo 'ACTION: test'
ACTION: test
+ echo 'IMPL: ada'
IMPL: ada
+ echo 'BUILD_IMPL: ada'
BUILD_IMPL: ada
+ echo 'MAL_IMPL: '
MAL_IMPL: 
+ '[' '' -a test = perf ']'
+ '[' '' -a '' ']'
+ '[' '' -a '' -a test = perf ']'
+ mode_var=ada_MODE
+ mode_val=
+ MAKE='make '
+ '[' -z '' ']'
[a lot more lines cut]
```

**Comment by kanaka** [comment]
@epylar what version of bash are you running? I don't see this with bash-4.3.46. I can't set a variable with a period in the name (so the mode logic should probably be fixed to account for that) but neither does it error for the variable name expansion like it is for you.

**Comment by epylar** [comment]
@kanaka I'm using:

```GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)```

**Comment by kanaka** [comment]
@epylar huh, okay. Must have made the variable name expansion more strict in 5. I think we could probably just translate `.` to `__` (double underscore) for mode variables. Want to take a stab at it?

**Comment by dubek** [comment]
This works for me locally with bash 4.4; @epylar can you try?

```diff
diff --git a/.travis_test.sh b/.travis_test.sh
index c4939dd5..e9b48d43 100755
--- a/.travis_test.sh
+++ b/.travis_test.sh
@@ -35,7 +35,8 @@ if [ "${NO_SELF_HOST_PERF}" -a "${DO_SELF_HOST}" -a "${ACTION}" = "perf" ]; then
     exit 0
 fi

-mode_var=${MAL_IMPL:-${IMPL}}_MODE
+raw_mode_var=${MAL_IMPL:-${IMPL}}_MODE
+mode_var=${raw_mode_var/./__}
 mode_val=${!mode_var}

 MAKE="make ${mode_val:+${mode_var}=${mode_val}}"
```

**Comment by epylar** [comment]
@dubek This patch works and passes tests for both `ada.2` and `python.2` on my system (calling with `./.travis_test.sh test ada.2` and `./.travis_test.sh test python.2`).

**Comment by epylar** [comment]
@kanaka Looks like @dubek solved it.
