### ISSUE TITLE
TCO in self-hosted mal

### ISSUE THREAD

**Issue by andrey-leshenko** [kanaka/mal#457]
It's unclear if the self-hosted mal implementation is supposed to have TCO.

The self-hosted version can inherit TCO from the mal language itself, but this requires the `apply` function from step 9 to also have TCO, which is not stated in the guide.

In my implementation, changing `apply` was the only thing necessary to get TCO working in the self-hosted implementation.
	
If this is the implied solution, maybe it is worth mentioning in the guide?

**Comment by kanaka** [comment]
@andrey-leshenko Sorry for the super slow reply. Somehow this slipped through the cracks. If you are still interested in this, I would be happy to consider a pull request updating the guide to mention this. I'm going to close this in the meantime.
