### ISSUE TITLE
defmacro! and mutating

### ISSUE THREAD

**Issue by rectalogic** [kanaka/mal#479]
The docs imply that `defmacro!` should set the `is_macro` attribute on the evaluated function (mutating it):

> Add a new attribute is_macro to mal function types
> Add a new special form defmacro!. This is very similar to the def! form, but before the evaluated value (mal function) is set in the environment, the is_macro attribute should be set to true.
https://github.com/kanaka/mal/blob/master/process/guide.md#step-8-macros

But meanwhile there is a test that the function is not mutated (52 of the implementations soft-fail this test):

> ;; Test that defining a macro does not mutate an existing function.
https://github.com/kanaka/mal/blob/master/tests/stepA_mal.mal#L291

e.g. `ada` fails (it mutates the function with `Set_Is_Macro()`)
https://github.com/kanaka/mal/blob/master/ada/stepa_mal.adb#L53
but `ada.2` passes (it creates a new function with the macro flag set and copies ast, params, env into it)
https://github.com/kanaka/mal/blob/master/ada.2/stepa_mal.adb#L162

So should the guide for `defmacro!` be changed to make clear the `is_macro` flag should not be mutated on the function?

**Comment by kanaka** [comment]
I left it vague intentionally. Ideally, the creation of a macro should copy the function without mutating it. But in some implementation languages, it's difficult to "clone" functions (specifically closures), so I left it vague but have a soft test to indicate if the implementation is doing the less ideal mutate in place. If you would like to adjust the guide slightly to indicate that non-mutating is better, but mutate in place will work, I would probably merge that in.

**Comment by dekrain** [comment]
My solution is to create a new construct `macro*`, which is the same as `fn*` but creates macros.
Example:
```lisp
(def! my-macro (macro* [a b] `(prn ~a (+ ~a ~b)) ))
(my-macro (do (prn "a") 1) (do (prn "b") 2))
; a a b 1 3
```

**Comment by kanaka** [comment]
I'm going to close this. @rectalogic if you want to submit a PR updating the guide to clarify that either option is reasonable, I would consider merging that. @dekrain that's a fine solution. If you then defined a `defmacro!` function that rewrites `fn*` to `macro*` then it should still pass the tests.
