### ISSUE TITLE
String reading clarification

### ISSUE THREAD

**Issue by DarkDust** [kanaka/mal#485]
In step 6, one of the tests is failing for my mal implementation since my interpreter is not reading a string correctly. The failing test is:

```
(read-string "\\"\\n\\"")
```

As far as I can see, this string is either ill-formed or I didn't understand the escaping of strings in mal. My interpreter sees `"\\"` and turns that into a string with single backslash. After that follows `\\n\\' (lacking any other rules, interpreted as symbol) plus the empty string `""`.

So, shouldn't the enclosed double quotes be escaped here? If not, what are the rules to correctly parse the string in that case?

**Comment by wasamasa** [comment]
I don't see any such test in the repository. The closest thing I could find is:

```clojure
(read-string "\"\n\"")
;=>"\n"
```

This string is interpreted as follows: String start, escaped double quote, escaped newline, escaped double quote, string end. This is turned into a string of three characters, double quote, newline, double quote. `read-string` interprets this as a string consisting of a single character, the newline. The interpreter prints it out as `"\n"`. Does that make sense to you?

**Comment by DarkDust** [comment]
My bad, the output of `make "test^foo^step6"` printed it the way I was quoting, the test is actually the one you cited and the error was that the newline wasn't escaped in my output. Thank you very much.
