### ISSUE TITLE
Tests for step6 neglect the requirement that atoms are not to be referenced only by name 

### ISSUE THREAD

**Issue by alimpfard** [kanaka/mal#490]
local atoms to `let*` are to be 'leaked' if they are closed over.
This might seem like an obvious requirement, but some languages can not store things by reference

```
(def! g (let* (atm (atom 0)) (fn* () (deref atm))))
(def! atm (atom 1))
(g)
;=>0
```

**Comment by kanaka** [comment]
@alimpfard that's a good test addition. I think most lexical closure reference bugs will be caught by other tests but there is still a possibility that test will catch something unique to atoms. Can you send a PR for it (and then close this ticket)? From Travis results we'll be able to see if there are any implementations that violate that test and fix them before merging the test update.

**Comment by kanaka** [comment]
I'm closing this in lieu of PR #493
