### ISSUE TITLE
Not able to run tests

### ISSUE THREAD

**Issue by wags-1314** [kanaka/mal#495]
I just forked the repo and wrote the program for the first step and I just got errors.

[output of `make "test^python3^step0".](https://github.com/kanaka/mal/files/4185413/err.txt)
[the parent Makefile.](https://hastebin.com/obilelejan.makefile)
[my python3 file.](https://hastebin.com/ajenicilib.py)
[my run file.](https://hastebin.com/yasebaboyu.bash)

Im running all these commands from cygwin

**Comment by kanaka** [comment]
@wags-1314 I don't a Windows system where I can easily run Cygwin. However, I do notice that you implementation is missing a loop so I would fix that problem first.

**Comment by wags-1314** [comment]
I recloned and ran it once again, and it started to work. It may have been the loop.
