### ISSUE TITLE
Slight tweak to regex

### ISSUE THREAD

**Issue by Discmonkey** [kanaka/mal#503]
While working through implementing step 6 of MAL, I ran into a strange issue where my tokenizer was grabbing "empty" tokens. 

After testing for a little bit, I noticed that the error was due to extra white spaces in any input. IE, (  + 4 4) produces these empty tokens. 

After looking at the regex it became pretty clear that the issue lies in the "symbol" match, which is currently represented as [^\s\[\]{}('"`,;)]*

The * character matches 0 or more, thus, it can return an empty, invalid match. 

The fix is to simply change the * to a +.

**Comment by kanaka** [comment]
@Discmonkey sorry for the really slow reply. I think there are some implementations with regex engines that don't properly support `+`. Most implementations that use regex tokenizing ignore any tokens that are empty by checking the token list after matching. I don't object to this in principle. If you are willing to send a PR with this improvement to the implementations that use this specific regex string (and perhaps removing the check for empty tokens), then we could see which implementations pass/fail in Travis. It could simplify the tokenizer for some implementations. But I would want to see most implementations that use this fixed before suggesting that in the guide.

**Comment by bjh21** [comment]
FWIW, my in-progress APL implementation hit a problem caused by that very `*`: the tokenizer kept matching, presumably at the end of the input, generating empty tokens and eventually consuming all my RAM in the process. I think this is a bug in GNU APL, but changing the expression to forbid empty matches worked around it.

**Comment by Discmonkey** [comment]
@kanaka ,

Thanks for your response. Let me do a quick pass over different implementations to see what uses regex engines, and which regex engines support +.

**Comment by kanaka** [comment]
@Discmonkey I'm closing this since it is pretty stale. If you ever get around to this, ping me and I'll re-open it.
