### ISSUE TITLE
Permissions Issues

### ISSUE THREAD

**Issue by jophde** [kanaka/mal#504]
I am getting the following when trying to run `make "python"` (or `make "go"`):
```
make python_MODE=python -C python step0_repl.py
make: make: Permission denied
make: *** [Makefile:350: python/step0_repl.py] Error 127
```
Both `python/run` and `go/run` have the execution bit set.  I also tried setting it anyway.  Interestingly if I run `make python_MODE=python -C python step0_repl.py` it works.

**Comment by kanaka** [comment]
@jophde just realized I never replied to this. Those commands work for me. Without more context I'm not sure what you are trying to do or what exactly is going wrong. `make python` doesn't actually build anything, it just makes sure the interpreted files exist. `make go` should compile the steps using the go executable.

**Comment by kanaka** [comment]
Closing due to no reply.
