### ISSUE TITLE
make doesn't work as expected

### ISSUE THREAD

**Issue by vrruiz** [kanaka/mal#536]
Step 0 says: ``Create a step0_repl.qx file in quux/``. 

However, by doing a ``make quux``, Makefile calls ``impls/quux``. In my case:

```
IMPLS = rust 
rust_STEP_TO_PROG =          rust/$($(1)).rs
```

```
[rvr@localhost mal]$ make "test^rust^step0"
make -C impls/step0_repl.rs rust/step0_repl.rs
make[1]: *** impls/step0_repl.rs: No existe el fichero o el directorio.  Alto.
make: *** [Makefile:390: rust/step0_repl.rs] Error 2
```

So, even if the path on the Makefile has been changed to ``rust/`` instead of ``impls/rust``, it goes to ``impls``.

**Comment by dubek** [comment]
Thanks @vrruiz  for noticing this and reporting. The Makefile is OK; the guide should be fixed.

Historically all the implementations were at the root of the project. At some point they were all moved to the `impls` directory and the Makefile was updated, but I assume there are missing places to fix in the guide.

If you wish, you can fix the guide in the relevant places and open a PR.

Again, thanks for reporting; hope you're having fun building your Mal implementation.
