### ISSUE TITLE
Floats don't work in the python implementation.

### ISSUE THREAD

**Issue by vipenzo** [kanaka/mal#646]
In the python implementation float numbers are not accepted by the reader.
There is a bug in reader.py at line 34 (read_atom function)

It is now:
   elif re.match(float_re, token): return int(token)
should be:
   elif re.match(float_re, token): return float(token)

**Comment by jero98772** [comment]
Hello , solve your problem , idk if my pull request will be accepted but here is how i solve it:

https://github.com/kanaka/mal/pull/654

i just change the line 34 to

 elif re.match(float_re, token): return float(token)

**Comment by kanaka** [comment]
This should be resolved now. Thanks for the catch!
