### ISSUE TITLE
vbs: Ubuntu install of python2 in WSL is failing in CI

### ISSUE THREAD

**Issue by kanaka** [kanaka/mal#680]
An unrelated change has revealed a new CI issue with vbs during the WSL deps step: https://github.com/kanaka/mal/actions/runs/10947930429/job/30398523790?pr=675

**Comment by kanaka** [comment]
@OldLiu001 care to take a look at this? I think it's failing during the python2 install step in WSL deps. I wonder if python3 would have less issue? runtest.py supports python3 (at some point in a year or two I may drop python2 support actually)

**Comment by OldLiu001** [comment]
@kanaka Seems to be an upstream repo issue (See [WSL/issues/10397](https://github.com/microsoft/WSL/issues/10397)), fixed in #682 and switched to `py3`.

**Comment by kanaka** [comment]
Resolved by #682. Thanks @OldLiu001!
