### ISSUE TITLE
runtest.py needs the ability to test expected failures

### ISSUE THREAD

**Issue by PhilipCollison** [kanaka/mal#90]
I am currently implementing mal in D and I've almost reached the end of step 1.

At the moment the only types I've implemented are symbols, lists, and vectors, but despite this I am passing the "string error" test for step 1.
## Actual ./mal Output:

> user> [1 2
> expected ], got EOF
> user> "abc
> abc
## Observed Test Output:

> TEST: (1 2 -> ["expected ')', got EOF\r\n",'*'] -> SUCCESS
> TEST: [1 2 -> ["expected ']', got EOF\r\n",'*'] -> SUCCESS
> TEST: "abc -> ['expected \'"\', got EOF\r\n','*'] -> SUCCESS

This issue is related to https://github.com/kanaka/mal/issues/89.

**Comment by kanaka** [comment]
Yep, runtest.py doesn't yet have a way to test for expected failures. So those tests are there but not actually doing anything except verifying that the implementation keeps going. It shouldn't be too hard to implement this, but it does mean that the error messages printed by the various implementations will need to be common enough to have some sort of regex match to verify that they did in fact throw an error.

**Comment by kanaka** [comment]
Support for this was added in f6f5d4f.
