### ISSUE TITLE
.gitignore */mal?

### ISSUE THREAD

**Issue by mrjbq7** [kanaka/mal#99]
Is there a reason you ``.gitignore`` the ``*/mal`` path?

It makes it hard to add files under ``factor/mal`` without using ``git add -f``...

**Comment by kanaka** [comment]
Some of the implementations also build the final executable as a file named mal. Unfortunately there is no way I know files by a name but not directories with that name. I've removed that and added the specific implementations that use that.

**Comment by mrjbq7** [comment]
Okay, thanks. I could have also fixed by making vocabularies named `mal-core` instead, I suppose.  If that makes it easier for you I can do that change.

**Comment by kanaka** [comment]
Nah, don't worry about it. */mal was too broad. But was added back when there was less than half as many implementations.

**Comment by mrjbq7** [comment]
I always thought binaries should be named after their stages, so final one would be ``stepA_mal``...

**Comment by kanaka** [comment]
Yes, that's true, but another thing that some implementation do in their Makefile is create a standalone mal program. For compiled languages, this usually just involves copying stepA_mal to mal. For the non-compiled languages, the intention is that all the dependent sources are copied (and lightly mangled as necessary to live in one file) into mal.EXT. For example, if you build mal.sh in the bash implementation, you will get an executable script named mal.sh that can be run standalone. This is implemented in a few language so far, but that's the background for why */mal was ignored (and someday I would like to continue to make the standalone mal program for every implementation)

**Comment by mrjbq7** [comment]
It would be a nice idea for Factor to have ``mal/mal.factor`` be the "final/full" implementation.  Then we could ``"mal" deploy`` and get a nice binary.

If you don't mind me asking, how would you suggest I do this?  Manually copy of the code from ``stepA_mal.factor`` (or vice versa)?  Make it a part of a ``make`` step?

Thanks,

**Comment by kanaka** [comment]
I would say create a make rule that compiles/deploys each of the steps. Then an additional rule would copy the compiled/deployed stepA_mal to mal/mal or something like that. There are quite a few examples of similar sorts of things in various implementations. For example, haskell/Makefile might be a good starting point.
